apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-test-tekton2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-test-tekton2 
  name: go-test-tekton2
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-test-tekton2 
